general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on    # تشغيل الشاشة فور الاستيقاظ
}

# المستمع الأول: قفل الشاشة بعد 5 دقائق (300 ثانية)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# المستمع الثاني: إطفاء الشاشة بعد 5 دقائق ونصف (330 ثانية)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off        # إطفاء الشاشة تماماً
    on-resume = hyprctl dispatch dpms on          # إعادة إضاءتها عند تحريك الماوس/الكيبورد
}
