-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 1.0,
        blur = {
            brightness = 1.01,
            passes = 2,
            size = 5,
        },
        inactive_opacity = 0.95,
        shadow = {
            color = "0xff613583",
            offset = "2 6",
            range = 0,
            render_power = 1,
        },
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(3584e4ff)", "rgba(ed333bff)"},
                angle = 45,
            },
        },
    },
    input = {
        kb_layout = "us,ara",
        kb_options = "grp:alt_shift_toggle",
    },
})

-- Bezier curves
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })
hl.curve("quick", { type = "bezier", points = { {0.15, 0.0}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadePopups",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.0,
    bezier = "default",
    style = "slidevert",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 5.2,
    bezier = "default",
    style = "slide",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 5.4,
    bezier = "default",
    style = "slide",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@120.03Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("foot"))
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + C")
hl.bind("SUPER + D", hl.dsp.exec_cmd("rofi -show drun"))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("waypaper"))
hl.unbind("SUPER + SHIFT + X")
hl.bind("SUPER + SHIFT + X", hl.dsp.window.move({ workspace = "special:magic" }))
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"))
hl.unbind("SUPER + SHIFT + C")
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("hyprpicker | wl-copy"))
hl.unbind("SUPER + V")
hl.bind("SUPER + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))

-- Window rules
hl.window_rule({
    match = {
        class = "^(waypaper)$",
    },
    float = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
